"""initial_schema

Revision ID: 64e435094c0f
Revises: 
Create Date: 2026-06-05 08:13:29.935811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64e435094c0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('authorization_ref', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_engagements_ends_after_starts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engagements'))
    )
    op.create_index('ix_engagements_active', 'engagements', ['is_active'], unique=False)
    op.create_table('hosts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('as_org', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('os_guess', sa.String(length=128), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_hosts_engagement_id_engagements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosts')),
    sa.UniqueConstraint('engagement_id', 'ip', name='ip')
    )
    op.create_index('ix_hosts_asn', 'hosts', ['asn'], unique=False)
    op.create_index('ix_hosts_country', 'hosts', ['country'], unique=False)
    op.create_index('ix_hosts_ip_gist', 'hosts', ['ip'], unique=False, postgresql_using='gist')
    op.create_table('scan_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('discovery', 'port_scan', 'banner_grab', 'enrich', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'authorizing', 'running', 'completed', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('requested_targets', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('authorized_targets', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('rejected_targets', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_scan_jobs_engagement_id_engagements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs'))
    )
    op.create_index('ix_scan_jobs_engagement', 'scan_jobs', ['engagement_id'], unique=False)
    op.create_index('ix_scan_jobs_status', 'scan_jobs', ['status'], unique=False)
    op.create_table('scope_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('cidr', postgresql.CIDR(), nullable=False),
    sa.Column('kind', sa.Enum('allow', 'deny', name='scope_kind'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_scope_entries_engagement_id_engagements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scope_entries')),
    sa.UniqueConstraint('engagement_id', 'cidr', 'kind', name='cidr_kind')
    )
    op.create_index('ix_scope_entries_cidr_gist', 'scope_entries', ['cidr'], unique=False, postgresql_using='gist')
    op.create_index('ix_scope_entries_engagement', 'scope_entries', ['engagement_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('scope_decision', 'job_submitted', 'job_started', 'job_finished', 'scope_changed', name='audit_action'), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], name=op.f('fk_audit_log_engagement_id_engagements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['scan_jobs.id'], name=op.f('fk_audit_log_job_id_scan_jobs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_engagement', 'audit_log', ['engagement_id'], unique=False)
    op.create_index('ix_audit_log_ts', 'audit_log', ['ts'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('transport', sa.Enum('tcp', 'udp', name='transport'), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('extra_info', sa.String(length=255), nullable=True),
    sa.Column('cpe', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('tls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('port >= 0 AND port <= 65535', name=op.f('ck_services_port_range')),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_services_host_id_hosts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('host_id', 'port', 'transport', name='host_port')
    )
    op.create_index('ix_services_port', 'services', ['port'], unique=False)
    op.create_index('ix_services_product', 'services', ['product'], unique=False)
    op.create_index('ix_services_search_gin', 'services', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_search_gin', table_name='services', postgresql_using='gin')
    op.drop_index('ix_services_product', table_name='services')
    op.drop_index('ix_services_port', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_audit_log_ts', table_name='audit_log')
    op.drop_index('ix_audit_log_engagement', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_scope_entries_engagement', table_name='scope_entries')
    op.drop_index('ix_scope_entries_cidr_gist', table_name='scope_entries', postgresql_using='gist')
    op.drop_table('scope_entries')
    op.drop_index('ix_scan_jobs_status', table_name='scan_jobs')
    op.drop_index('ix_scan_jobs_engagement', table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index('ix_hosts_ip_gist', table_name='hosts', postgresql_using='gist')
    op.drop_index('ix_hosts_country', table_name='hosts')
    op.drop_index('ix_hosts_asn', table_name='hosts')
    op.drop_table('hosts')
    op.drop_index('ix_engagements_active', table_name='engagements')
    op.drop_table('engagements')
    # ### end Alembic commands ###
